#include "DTEngine.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <type_traits>
namespace drafting_table::ipad { namespace {
constexpr std::uint32_t kVersion1=1,kVersion2=2,kVersion3=3; constexpr std::size_t kMaxBytes=64u*1024u*1024u; constexpr std::uint32_t kMaxPages=1000,kMaxLayers=1000,kMaxStrokes=100000,kMaxPoints=1000000; constexpr std::uint64_t kMaxTotalPoints=2000000; constexpr std::uint32_t kMaxString=4096;
template<class T> struct Bits{using type=std::make_unsigned_t<T>;}; template<>struct Bits<float>{using type=std::uint32_t;}; template<>struct Bits<double>{using type=std::uint64_t;};
template<class T> void put(std::vector<std::uint8_t>&o,T v){using U=typename Bits<T>::type;U b{};if constexpr(std::is_same_v<T,float>||std::is_same_v<T,double>)std::memcpy(&b,&v,sizeof v);else b=(U)v;for(size_t i=0;i<sizeof(U);++i)o.push_back((uint8_t)(b>>(8*i)));}
template<class T> bool get(std::span<const uint8_t>d,size_t&a,T&v){using U=typename Bits<T>::type;if(a>d.size()||sizeof(U)>d.size()-a)return false;U b=0;for(size_t i=0;i<sizeof(U);++i)b|=(U)d[a++]<<(8*i);if constexpr(std::is_same_v<T,float>||std::is_same_v<T,double>)std::memcpy(&v,&b,sizeof v);else v=(T)b;return true;}
bool style(float s,float o,std::uint32_t,float hardness){return std::isfinite(s)&&std::isfinite(o)&&s>=1&&s<=40&&o>=.05f&&o<=1&&std::isfinite(hardness)&&hardness>=0&&hardness<=1;}
bool validTool(std::uint8_t raw){return raw<=static_cast<std::uint8_t>(DTTool::Bucket);}
bool point(const PencilSample&p){return std::isfinite(p.x)&&std::isfinite(p.y)&&std::isfinite(p.pressure)&&p.pressure>=0&&p.pressure<=1&&std::isfinite(p.altitude)&&std::isfinite(p.azimuth)&&std::isfinite(p.roll)&&std::isfinite(p.hoverDistance)&&std::isfinite(p.timestamp);}
bool nameOK(const std::string&n){return n.size()<=kMaxString;}
void putString(std::vector<uint8_t>&o,const std::string&s){put<uint32_t>(o,(uint32_t)s.size());o.insert(o.end(),s.begin(),s.end());}
bool getString(std::span<const uint8_t>d,size_t&a,std::string&s){uint32_t n=0;if(!get(d,a,n)||n>kMaxString||n>d.size()-a)return false;s.assign((const char*)d.data()+a,n);a+=n;return true;}
void putStroke(std::vector<uint8_t>&o,const Stroke&s){o.push_back((uint8_t)s.tool);o.insert(o.end(),3,0);put<float>(o,s.brushSize);put<float>(o,s.brushOpacity);put<uint32_t>(o,s.brushColorRGBA);put<float>(o,s.brushHardness);put<uint32_t>(o,(uint32_t)s.points.size());for(auto&p:s.points){put<float>(o,p.x);put<float>(o,p.y);put<float>(o,p.pressure);put<float>(o,p.altitude);put<float>(o,p.azimuth);put<float>(o,p.roll);put<float>(o,p.hoverDistance);put<double>(o,p.timestamp);put<uint64_t>(o,p.id);put<uint64_t>(o,p.estimationUpdateIndex);put<uint64_t>(o,p.estimationId);put<uint32_t>(o,(uint32_t)p.flags);}}
bool getStroke(std::span<const uint8_t>d,size_t&a,Stroke&s,uint64_t&total,uint32_t version){if(a>=d.size())return false;uint8_t raw=d[a++];if(!validTool(raw)||(version<3&&raw>1)||a+3>d.size())return false;a+=3;s.tool=(DTTool)raw;uint32_t n=0,flags=0;if(!get(d,a,s.brushSize)||!get(d,a,s.brushOpacity))return false;if(version>=3){if(!get(d,a,s.brushColorRGBA)||!get(d,a,s.brushHardness))return false;}else{s.brushColorRGBA=kDefaultBrushColorRGBA;s.brushHardness=kDefaultBrushHardness;}if(!get(d,a,n)||!style(s.brushSize,s.brushOpacity,s.brushColorRGBA,s.brushHardness)||n>kMaxPoints||total+n>kMaxTotalPoints)return false;total+=n;s.points.reserve(n);for(uint32_t j=0;j<n;++j){PencilSample p;if(!get(d,a,p.x)||!get(d,a,p.y)||!get(d,a,p.pressure)||!get(d,a,p.altitude)||!get(d,a,p.azimuth)||!get(d,a,p.roll)||!get(d,a,p.hoverDistance)||!get(d,a,p.timestamp)||!get(d,a,p.id)||!get(d,a,p.estimationUpdateIndex)||!get(d,a,p.estimationId)||!get(d,a,flags)||!point(p)||(flags&~0x7fu))return false;p.flags=(SampleFlags)flags;s.points.push_back(p);}return true;}
}}
namespace drafting_table::ipad {
Engine::Engine(){pages_.push_back(Page{});pages_[0].layers.push_back(Layer{});}
DTTool Engine::tool()const{std::lock_guard l(mutex_);return tool_;} void Engine::setTool(DTTool v){std::lock_guard l(mutex_);if(static_cast<std::uint8_t>(v)>static_cast<std::uint8_t>(DTTool::Bucket))v=DTTool::Brush;if(tool_!=v){tool_=v;++revision_;}}
float Engine::brushSize()const{std::lock_guard l(mutex_);return brushSize_;} void Engine::setBrushSize(float v){std::lock_guard l(mutex_);v=std::isfinite(v)?std::clamp(v,1.f,40.f):8.f;if(v!=brushSize_){brushSize_=v;++revision_;}}
float Engine::brushOpacity()const{std::lock_guard l(mutex_);return brushOpacity_;} void Engine::setBrushOpacity(float v){std::lock_guard l(mutex_);v=std::isfinite(v)?std::clamp(v,.05f,1.f):1.f;if(v!=brushOpacity_){brushOpacity_=v;++revision_;}}
std::uint32_t Engine::brushColorRGBA()const{std::lock_guard l(mutex_);return brushColorRGBA_;} void Engine::setBrushColorRGBA(std::uint32_t v){std::lock_guard l(mutex_);if(brushColorRGBA_!=v){brushColorRGBA_=v;++revision_;}}
float Engine::brushHardness()const{std::lock_guard l(mutex_);return brushHardness_;} void Engine::setBrushHardness(float v){std::lock_guard l(mutex_);v=std::isfinite(v)?std::clamp(v,0.f,1.f):kDefaultBrushHardness;if(v!=brushHardness_){brushHardness_=v;++revision_;}}
void Engine::beginStroke(){std::lock_guard l(mutex_);if(strokeInProgress_)cancelStrokeUnlocked();activeStroke_={};activeStroke_.tool=tool_;activeStroke_.brushSize=brushSize_;activeStroke_.brushOpacity=brushOpacity_;activeStroke_.brushColorRGBA=brushColorRGBA_;activeStroke_.brushHardness=brushHardness_;StrokeConfig c;c.brushSize=brushSize_;inputEngine_.beginStroke(c);strokeInProgress_=true;++revision_;}
void Engine::appendSamples(std::span<const PencilSample>r,std::span<const PencilSample>p){std::lock_guard l(mutex_);if(!strokeInProgress_)return;inputEngine_.appendSamples(r,p);rebuildActiveStroke();++revision_;}
bool Engine::updateEstimatedSample(uint64_t i,const PencilSample&p){std::lock_guard l(mutex_);if(!strokeInProgress_)return false;bool ok=inputEngine_.updateEstimatedSampleByIndex(i,p);if(ok){rebuildActiveStroke();++revision_;}return ok;}
void Engine::rebuildActiveStroke(){activeStroke_.points=inputEngine_.realSamples();activeStroke_.points.insert(activeStroke_.points.end(),inputEngine_.predictedSamples().begin(),inputEngine_.predictedSamples().end());}
void Engine::cancelStrokeUnlocked(){inputEngine_.cancelStroke();activeStroke_.points.clear();strokeInProgress_=false;}
void Engine::endStroke(){std::lock_guard l(mutex_);if(!strokeInProgress_)return;if(!inputEngine_.realSamples().empty()){activeLayerUnlocked().strokes.push_back(activeStroke_);activeLayerUnlocked().strokes.back().points=inputEngine_.realSamples();activeLayerUnlocked().redoStrokes.clear();}inputEngine_.endStroke();inputEngine_.clearCommittedSamples();activeStroke_.points.clear();strokeInProgress_=false;++revision_;}
void Engine::cancelStroke(){std::lock_guard l(mutex_);cancelStrokeUnlocked();++revision_;}
void Engine::clear(){std::lock_guard l(mutex_);cancelStrokeUnlocked();inputEngine_.clearCommittedSamples();auto&ly=activeLayerUnlocked();ly.strokes.clear();ly.redoStrokes.clear();++revision_;}
bool Engine::undoLastStroke(){std::lock_guard l(mutex_);bool c=false;if(strokeInProgress_){cancelStrokeUnlocked();c=true;}auto&ly=activeLayerUnlocked();if(!ly.strokes.empty()){ly.redoStrokes.push_back(std::move(ly.strokes.back()));ly.strokes.pop_back();c=true;}if(c)++revision_;return c;}
bool Engine::redoLastStroke(){std::lock_guard l(mutex_);bool c=false;if(strokeInProgress_){cancelStrokeUnlocked();c=true;}auto&ly=activeLayerUnlocked();if(!ly.redoStrokes.empty()){ly.strokes.push_back(std::move(ly.redoStrokes.back()));ly.redoStrokes.pop_back();c=true;}if(c)++revision_;return c;}
bool Engine::canUndo()const{std::lock_guard l(mutex_);return strokeInProgress_||!activeLayerUnlocked().strokes.empty();} bool Engine::canRedo()const{std::lock_guard l(mutex_);return !activeLayerUnlocked().redoStrokes.empty();}
bool Engine::moveStrokes(std::span<const std::size_t> indices, float dx, float dy){std::lock_guard l(mutex_);if(indices.empty()||!std::isfinite(dx)||!std::isfinite(dy))return false;auto& ly=activeLayerUnlocked();for(auto idx:indices){if(idx<ly.strokes.size()){for(auto& pt:ly.strokes[idx].points){pt.x+=dx;pt.y+=dy;}}}++revision_;return true;}
bool Engine::scaleStrokes(std::span<const std::size_t> indices, float sx, float sy, float originX, float originY){std::lock_guard l(mutex_);if(indices.empty()||!std::isfinite(sx)||!std::isfinite(sy)||!std::isfinite(originX)||!std::isfinite(originY))return false;auto& ly=activeLayerUnlocked();for(auto idx:indices){if(idx<ly.strokes.size()){for(auto& pt:ly.strokes[idx].points){pt.x=originX+(pt.x-originX)*sx;pt.y=originY+(pt.y-originY)*sy;}}}++revision_;return true;}
bool Engine::rotateStrokes(std::span<const std::size_t> indices, float angleRad, float originX, float originY){std::lock_guard l(mutex_);if(indices.empty()||!std::isfinite(angleRad)||!std::isfinite(originX)||!std::isfinite(originY))return false;auto& ly=activeLayerUnlocked();const float cosA=cosf(angleRad);const float sinA=sinf(angleRad);for(auto idx:indices){if(idx<ly.strokes.size()){for(auto& pt:ly.strokes[idx].points){const float dx=pt.x-originX;const float dy=pt.y-originY;pt.x=originX+dx*cosA-dy*sinA;pt.y=originY+dx*sinA+dy*cosA;}}}++revision_;return true;}
bool Engine::deleteStrokes(std::span<const std::size_t> indices){std::lock_guard l(mutex_);if(indices.empty())return false;auto& ly=activeLayerUnlocked();std::vector<bool> toRemove(ly.strokes.size(),false);for(auto idx:indices)if(idx<ly.strokes.size())toRemove[idx]=true;std::vector<Stroke> rem;rem.reserve(ly.strokes.size());for(size_t i=0;i<ly.strokes.size();++i)if(!toRemove[i])rem.push_back(std::move(ly.strokes[i]));ly.strokes=std::move(rem);ly.redoStrokes.clear();++revision_;return true;}
bool Engine::duplicateStrokes(std::span<const std::size_t> indices, float dx, float dy){std::lock_guard l(mutex_);if(indices.empty())return false;auto& ly=activeLayerUnlocked();std::vector<Stroke> copies;copies.reserve(indices.size());for(auto idx:indices){if(idx<ly.strokes.size()){Stroke c=ly.strokes[idx];for(auto& pt:c.points){pt.x+=dx;pt.y+=dy;}copies.push_back(std::move(c));}}for(auto& c:copies)ly.strokes.push_back(std::move(c));ly.redoStrokes.clear();++revision_;return true;}
std::size_t Engine::hitTestStroke(float x, float y, float tolerance) const {std::lock_guard l(mutex_);const auto& ly=activeLayerUnlocked();if(!ly.visible||ly.opacity<=0.0f||ly.strokes.empty())return std::numeric_limits<std::size_t>::max();for(std::size_t i=ly.strokes.size();i>0;--i){const std::size_t idx=i-1;const auto& s=ly.strokes[idx];const float r=(tolerance+s.brushSize*0.5f);const float r2=r*r;for(std::size_t j=0;j<s.points.size();++j){const float dx=s.points[j].x-x;const float dy=s.points[j].y-y;if(dx*dx+dy*dy<=r2)return idx;if(j+1<s.points.size()){const float x1=s.points[j].x;const float y1=s.points[j].y;const float x2=s.points[j+1].x;const float y2=s.points[j+1].y;const float segDx=x2-x1;const float segDy=y2-y1;const float segLen2=segDx*segDx+segDy*segDy;if(segLen2>0.0001f){const float t=std::clamp(((x-x1)*segDx+(y-y1)*segDy)/segLen2,0.0f,1.0f);const float pdx=x-(x1+t*segDx);const float pdy=y-(y1+t*segDy);if(pdx*pdx+pdy*pdy<=r2)return idx;}}}}return std::numeric_limits<std::size_t>::max();}
bool Engine::addStroke(const Stroke& stroke){std::lock_guard l(mutex_);if(stroke.points.empty())return false;auto& ly=activeLayerUnlocked();ly.strokes.push_back(stroke);ly.redoStrokes.clear();++revision_;return true;}
std::size_t Engine::activeLayerStrokeCount()const{std::lock_guard l(mutex_);return activeLayerUnlocked().strokes.size();}
std::size_t Engine::pageCount()const{std::lock_guard l(mutex_);return pages_.size();} std::size_t Engine::activePageIndex()const{std::lock_guard l(mutex_);return activePage_;} std::size_t Engine::activeLayerIndex()const{std::lock_guard l(mutex_);return activePageUnlocked().activeLayer;}
std::vector<std::string> Engine::pageNames()const{std::lock_guard l(mutex_);std::vector<std::string>r;for(auto&p:pages_)r.push_back(p.name);return r;} std::vector<std::string> Engine::layerNames()const{std::lock_guard l(mutex_);std::vector<std::string>r;for(auto&x:activePageUnlocked().layers)r.push_back(x.name);return r;}
bool Engine::addPage(const std::string&n){std::lock_guard l(mutex_);if(!nameOK(n)||pages_.size()>=kMaxPages)return false;cancelStrokeUnlocked();Page p;p.name=n.empty()?"Page "+std::to_string(pages_.size()+1):n;p.layers.push_back(Layer{});pages_.push_back(std::move(p));activePage_=pages_.size()-1;++revision_;return true;}
bool Engine::selectPage(size_t i){std::lock_guard l(mutex_);if(i>=pages_.size())return false;const bool cancelled=strokeInProgress_;cancelStrokeUnlocked();if(activePage_!=i||cancelled){activePage_=i;++revision_;}return true;}
bool Engine::deletePage(size_t i){std::lock_guard l(mutex_);if(i>=pages_.size()||pages_.size()<=1)return false;cancelStrokeUnlocked();pages_.erase(pages_.begin()+i);if(activePage_>=pages_.size())activePage_=pages_.size()-1;else if(activePage_>i)--activePage_;++revision_;return true;}
bool Engine::renamePage(size_t i,const std::string&n){std::lock_guard l(mutex_);if(i>=pages_.size()||n.empty()||!nameOK(n))return false;pages_[i].name=n;++revision_;return true;}
std::size_t Engine::duplicatePage(size_t i){std::lock_guard l(mutex_);if(i>=pages_.size()||pages_.size()>=kMaxPages)return std::numeric_limits<std::size_t>::max();cancelStrokeUnlocked();Page copy=pages_[i];copy.name=pages_[i].name+" Copy";for(std::size_t n=2;;++n){bool used=false;for(const auto&p:pages_)if(p.name==copy.name){used=true;break;}if(!used)break;copy.name=pages_[i].name+" Copy "+std::to_string(n);}for(auto&ly:copy.layers)ly.redoStrokes.clear();pages_.insert(pages_.begin()+i+1,std::move(copy));activePage_=i+1;++revision_;return activePage_;}
bool Engine::movePage(size_t from,size_t to){std::lock_guard l(mutex_);if(from>=pages_.size()||to>=pages_.size()||from==to)return from<pages_.size();cancelStrokeUnlocked();Page moved=std::move(pages_[from]);pages_.erase(pages_.begin()+from);pages_.insert(pages_.begin()+to,std::move(moved));if(activePage_==from)activePage_=to;else if(from<activePage_&&activePage_<=to)--activePage_;else if(to<=activePage_&&activePage_<from)++activePage_;++revision_;return true;}
bool Engine::addLayer(const std::string&n){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(!nameOK(n)||p.layers.size()>=kMaxLayers)return false;cancelStrokeUnlocked();Layer x;x.name=n.empty()?"Layer "+std::to_string(p.layers.size()+1):n;p.layers.push_back(std::move(x));p.activeLayer=p.layers.size()-1;++revision_;return true;}
bool Engine::selectLayer(size_t i){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(i>=p.layers.size())return false;const bool cancelled=strokeInProgress_;cancelStrokeUnlocked();if(p.activeLayer!=i||cancelled){p.activeLayer=i;++revision_;}return true;}
bool Engine::deleteLayer(size_t i){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(i>=p.layers.size()||p.layers.size()<=1)return false;cancelStrokeUnlocked();p.layers.erase(p.layers.begin()+i);if(p.activeLayer>=p.layers.size())p.activeLayer=p.layers.size()-1;else if(p.activeLayer>i)--p.activeLayer;++revision_;return true;}
bool Engine::renameLayer(size_t i,const std::string&n){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(i>=p.layers.size()||n.empty()||!nameOK(n))return false;p.layers[i].name=n;++revision_;return true;}
std::size_t Engine::duplicateLayer(size_t i){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(i>=p.layers.size()||p.layers.size()>=kMaxLayers)return std::numeric_limits<std::size_t>::max();cancelStrokeUnlocked();Layer copy=p.layers[i];copy.name=p.layers[i].name+" Copy";for(std::size_t n=2;;++n){bool used=false;for(const auto&ly:p.layers)if(ly.name==copy.name){used=true;break;}if(!used)break;copy.name=p.layers[i].name+" Copy "+std::to_string(n);}copy.redoStrokes.clear();p.layers.insert(p.layers.begin()+i+1,std::move(copy));p.activeLayer=i+1;++revision_;return p.activeLayer;}
bool Engine::moveLayer(size_t from,size_t to){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(from>=p.layers.size()||to>=p.layers.size()||from==to)return from<p.layers.size();cancelStrokeUnlocked();Layer moved=std::move(p.layers[from]);p.layers.erase(p.layers.begin()+from);p.layers.insert(p.layers.begin()+to,std::move(moved));if(p.activeLayer==from)p.activeLayer=to;else if(from<p.activeLayer&&p.activeLayer<=to)--p.activeLayer;else if(to<=p.activeLayer&&p.activeLayer<from)++p.activeLayer;++revision_;return true;}
bool Engine::activeLayerVisible()const{std::lock_guard l(mutex_);return activeLayerUnlocked().visible;} bool Engine::setActiveLayerVisible(bool v){std::lock_guard l(mutex_);auto&x=activeLayerUnlocked();if(x.visible==v)return true;x.visible=v;++revision_;return true;}
float Engine::activeLayerOpacity()const{std::lock_guard l(mutex_);return activeLayerUnlocked().opacity;} bool Engine::setActiveLayerOpacity(float v){std::lock_guard l(mutex_);if(!std::isfinite(v))return false;auto&x=activeLayerUnlocked();v=std::clamp(v,0.f,1.f);if(x.opacity!=v){x.opacity=v;++revision_;}return true;}
bool Engine::layerVisible(size_t i)const{std::lock_guard l(mutex_);const auto&p=activePageUnlocked();return i<p.layers.size()?p.layers[i].visible:false;} float Engine::layerOpacity(size_t i)const{std::lock_guard l(mutex_);const auto&p=activePageUnlocked();return i<p.layers.size()?p.layers[i].opacity:0.f;}
bool Engine::setLayerVisible(size_t i,bool v){std::lock_guard l(mutex_);auto&p=activePageUnlocked();if(i>=p.layers.size())return false;if(p.layers[i].visible!=v){p.layers[i].visible=v;++revision_;}return true;} bool Engine::setLayerOpacity(size_t i,float v){std::lock_guard l(mutex_);if(!std::isfinite(v))return false;auto&p=activePageUnlocked();if(i>=p.layers.size())return false;v=std::clamp(v,0.f,1.f);if(p.layers[i].opacity!=v){p.layers[i].opacity=v;++revision_;}return true;}
std::vector<Stroke> Engine::snapshot()const{std::lock_guard l(mutex_);return snapshotForPageUnlocked(activePage_);}
std::vector<Stroke> Engine::snapshotForPage(std::size_t pageIndex)const{std::lock_guard l(mutex_);return snapshotForPageUnlocked(pageIndex);}
std::vector<Stroke> Engine::snapshotForPageUnlocked(std::size_t pageIndex)const{std::vector<Stroke>r;if(pageIndex>=pages_.size())return r;const auto&pg=pages_[pageIndex];for(auto&ly:pg.layers)if(ly.visible&&ly.opacity>0){for(auto&s:ly.strokes){auto c=s;c.brushOpacity*=ly.opacity;r.push_back(std::move(c));}}if(pageIndex==activePage_&&strokeInProgress_&&!activeStroke_.points.empty()){auto c=activeStroke_;c.brushOpacity*=activeLayerUnlocked().opacity;if(activeLayerUnlocked().visible&&activeLayerUnlocked().opacity>0)r.push_back(std::move(c));}return r;}
std::vector<Stroke> Engine::snapshotForDisplay(std::size_t pageIndex,std::size_t maxPointsPerStroke,std::size_t maxTotalPoints)const{
 std::lock_guard l(mutex_);std::vector<Stroke> result;if(pageIndex>=pages_.size()||maxPointsPerStroke==0||maxTotalPoints==0)return result;std::size_t total=0;
 auto append=[&](const Stroke&source,float layerOpacity){if(source.points.empty()||total>=maxTotalPoints)return;const std::size_t count=std::min({source.points.size(),maxPointsPerStroke,maxTotalPoints-total});if(count==0)return;Stroke copy;copy.tool=source.tool;copy.brushSize=source.brushSize;copy.brushOpacity=source.brushOpacity*layerOpacity;copy.brushColorRGBA=source.brushColorRGBA;copy.brushHardness=source.brushHardness;copy.points.reserve(count);if(count==source.points.size())copy.points=source.points;else if(count==1)copy.points.push_back(source.points.back());else{const double stride=static_cast<double>(source.points.size()-1)/static_cast<double>(count-1);for(std::size_t i=0;i<count;++i){const auto index=std::min(source.points.size()-1,static_cast<std::size_t>(std::llround(static_cast<double>(i)*stride)));copy.points.push_back(source.points[index]);}}total+=copy.points.size();result.push_back(std::move(copy));};
 const auto&page=pages_[pageIndex];for(const auto&layer:page.layers){if(!layer.visible||layer.opacity<=0)continue;for(const auto&stroke:layer.strokes){append(stroke,layer.opacity);if(total>=maxTotalPoints)break;}if(total>=maxTotalPoints)break;}if(pageIndex==activePage_&&strokeInProgress_&&activeLayerUnlocked().visible&&activeLayerUnlocked().opacity>0&&total<maxTotalPoints)append(activeStroke_,activeLayerUnlocked().opacity);return result;
}
std::size_t Engine::strokeCount()const{std::lock_guard l(mutex_);size_t n=0;for(auto&s:activePageUnlocked().layers)n+=s.strokes.size();if(strokeInProgress_&&!activeStroke_.points.empty())++n;return n;} std::size_t Engine::sampleCount()const{std::lock_guard l(mutex_);size_t n=0;for(auto&ly:activePageUnlocked().layers)for(auto&s:ly.strokes)n+=s.points.size();if(strokeInProgress_)n+=activeStroke_.points.size();return n;} std::uint64_t Engine::revision()const{std::lock_guard l(mutex_);return revision_;}

std::vector<uint8_t> Engine::archive()const{std::lock_guard l(mutex_);if(pages_.empty()||pages_.size()>kMaxPages||activePage_>=pages_.size()||!style(brushSize_,brushOpacity_,brushColorRGBA_,brushHardness_))return{};size_t sz=36;uint64_t total=0;for(auto&p:pages_){if(p.name.empty()||!nameOK(p.name)||p.layers.empty()||p.layers.size()>kMaxLayers||p.activeLayer>=p.layers.size())return{};sz+=12+p.name.size();for(auto&ly:p.layers){if(ly.name.empty()||!nameOK(ly.name)||!std::isfinite(ly.opacity)||ly.opacity<0||ly.opacity>1||ly.strokes.size()>kMaxStrokes)return{};sz+=13+ly.name.size();for(auto&s:ly.strokes){if(s.points.size()>kMaxPoints||!style(s.brushSize,s.brushOpacity,s.brushColorRGBA,s.brushHardness)||total+s.points.size()>kMaxTotalPoints)return{};total+=s.points.size();sz+=24+s.points.size()*64;for(auto&pnt:s.points)if(!point(pnt))return{};}}}if(sz>kMaxBytes)return{};std::vector<uint8_t>o;o.reserve(sz);o.insert(o.end(),{'D','T','A','R'});put<uint32_t>(o,kVersion3);put<uint32_t>(o,(uint32_t)activePage_);put<uint32_t>(o,(uint32_t)pages_.size());o.push_back((uint8_t)tool_);o.insert(o.end(),3,0);put<float>(o,brushSize_);put<float>(o,brushOpacity_);put<uint32_t>(o,brushColorRGBA_);put<float>(o,brushHardness_);for(auto&p:pages_){putString(o,p.name);put<uint32_t>(o,(uint32_t)p.activeLayer);put<uint32_t>(o,(uint32_t)p.layers.size());for(auto&ly:p.layers){putString(o,ly.name);o.push_back(ly.visible?1:0);put<float>(o,ly.opacity);put<uint32_t>(o,(uint32_t)ly.strokes.size());for(auto&s:ly.strokes)putStroke(o,s);}}return o;}
bool Engine::loadArchive(std::span<const uint8_t>d){if(d.size()<12||d.size()>kMaxBytes)return false;size_t a=0;if(d[a++]!='D'||d[a++]!='T'||d[a++]!='A'||d[a++]!='R')return false;uint32_t ver=0;if(!get(d,a,ver)||ver<kVersion1||ver>kVersion3)return false;std::vector<Page> pages;size_t activePage=0;DTTool tool=DTTool::Brush;float bs=8,bo=1,hardness=kDefaultBrushHardness;std::uint32_t color=kDefaultBrushColorRGBA;uint64_t total=0;
if(ver==1){uint32_t count=0;if(!get(d,a,count)||count>kMaxStrokes)return false;Page p;p.layers.push_back(Layer{});for(uint32_t i=0;i<count;++i){Stroke s;if(!getStroke(d,a,s,total,1))return false;p.layers[0].strokes.push_back(std::move(s));}if(a!=d.size())return false;pages.push_back(std::move(p));}
else {uint32_t ap=0,np=0;uint8_t raw=0;if(!get(d,a,ap)||!get(d,a,np)||ap>=np||np==0||np>kMaxPages||a>=d.size())return false;raw=d[a++];if(!validTool(raw)||(ver<3&&raw>1)||a+3>d.size())return false;a+=3;if(!get(d,a,bs)||!get(d,a,bo)||!style(bs,bo,color,hardness))return false;if(ver>=3){if(!get(d,a,color)||!get(d,a,hardness)||!style(bs,bo,color,hardness))return false;}activePage=ap;pages.reserve(np);for(uint32_t i=0;i<np;++i){Page p;uint32_t al=0,nl=0;if(!getString(d,a,p.name)||p.name.empty()||!get(d,a,al)||!get(d,a,nl)||nl==0||nl>kMaxLayers||al>=nl)return false;p.activeLayer=al;p.layers.reserve(nl);for(uint32_t j=0;j<nl;++j){Layer ly;uint8_t vis=0;uint32_t ns=0;if(!getString(d,a,ly.name)||ly.name.empty()||a>=d.size())return false;vis=d[a++];if(vis>1||!get(d,a,ly.opacity)||ly.opacity<0||ly.opacity>1||!get(d,a,ns)||ns>kMaxStrokes)return false;ly.visible=vis!=0;ly.strokes.reserve(ns);for(uint32_t k=0;k<ns;++k){Stroke s;if(!getStroke(d,a,s,total,ver))return false;ly.strokes.push_back(std::move(s));}p.layers.push_back(std::move(ly));}pages.push_back(std::move(p));}if(a!=d.size())return false;tool=(DTTool)raw;}
std::lock_guard l(mutex_);cancelStrokeUnlocked();inputEngine_.clearCommittedSamples();pages_=std::move(pages);activePage_=activePage;tool_=tool;brushSize_=bs;brushOpacity_=bo;brushColorRGBA_=color;brushHardness_=hardness;++revision_;return true;}
}
